Fix 'crate rustc_ast_pretty required to be available in rlib format'
    error: crate `rustc_ast_pretty` required to be available in rlib format, but was not found in this form
      |
      = help: try adding `extern crate rustc_driver;` at the top level of this crate

    error: crate `tracing` required to be available in rlib format, but was not found in this form

    error: could not compile `prettyplease-update-examples` due to 2 previous errors